platform :ios,'7.0'
pod 'AFNetworking'              # 网络请求
pod 'JSONModel'                 # JSON和对象互转
pod 'BlocksKit'                 # cocoa api Blocks 扩展
pod 'UIActionSheet+Blocks'      # 同上
pod 'UIAlertView+Blocks'        # 同上
pod 'RefreshControl'            # 刷新控件
pod 'JGProgressHUD'             # 土司框
pod 'FMDB'                      # sqlite
pod 'FMDB/SQLCipher'            # sqllite cipher
pod 'SSKeychain'                # 钥匙串
pod 'JBChartView'               # 绘制图表
pod 'A3ParallaxScrollView'      # 下拉顶部图片拉伸效果
# https://github.com/michaelhenry/MHYahooParallaxView              # 视察效果，启动动画
