#!/bin/bash
# Program:
#       This program shows the user's choice
# History:
# 2005/08/25    VBird   First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

read -p "Please input (Y/N): " yn

if [ "$yn" == "Y" -o "$yn" == "y" ];then
	echo "Ok,continue"
elif [ "$yn" == "N" -o "$yn" == "n" ];then
	echo "Oh,interrupt!"
else
	echo "I don't know what you choice is"
fi
